version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST={REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
